# Generated by Django 5.1.2 on 2024-11-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_remove_user_fecha_registro_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oportunidad', models.CharField(max_length=50, unique=True)),
                ('campana', models.IntegerField()),
                ('cod_proveedor', models.CharField(max_length=5)),
                ('fecha_captacion', models.DateTimeField()),
                ('nombre', models.CharField(max_length=50)),
                ('ape1', models.CharField(blank=True, max_length=50)),
                ('ape2', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('memo', models.JSONField()),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
