# Generated by Django 5.1.2 on 2024-11-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auxcampanadisociar_auxcampanas_auxdisociar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsleads',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wsleads',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
